services:
  - type: web
    name: my-service
    env: python
    plan: free  # You can choose a different plan as needed
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Update and install system dependencies
      apt-get update && apt-get install -y gcc g++ openjdk-11-jdk build-essential

      # Check Java installation
      java -version
      javac -version

      # Collect static files
      python manage.py collectstatic --noinput
      
      # Make migrations
      python manage.py makemigrations
      
      # Apply migrations
      python manage.py migrate
    startCommand: |
      # Start your Django application
      gunicorn VCube_Data_API.wsgi --bind 0.0.0.0:8000

  - type: cron
    name: my-cron-job
    schedule: "0 0 * * *"
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt

      # Update and install system dependencies
      apt-get update && apt-get install -y gcc g++ openjdk-11-jdk build-essential

      # Check Java installation
      java -version
      javac -version

    startCommand: |
      # Run your cron job command
      python manage.py my_cron_command
