services:
  - type: web
    name: my-django-service
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn VCube_Data_API.wsgi.application"
